#? Config file for btop v. 1.4.0

color_theme = "catppuccin_macchiato"

#* If the theme set background should be shown, set to False if you want terminal background transparency
theme_background = True

#* Sets if 256 or 24-bit colors should be used
truecolor = True

#* Rounded corners on boxes, is ignored if TTY mode is ON
rounded_corners = True

#* Default symbols to use for graph creation, "braille", "block" or "tty"
graph_symbol = "braille"

#* Update time in milliseconds, recommended 2000 ms or above for better sample times for processes
update_ms = 2000

#* Processes sorting, "pid" "program" "arguments" "threads" "user" "memory" "cpu lazy" "cpu direct"
proc_sorting = "cpu lazy"

#* Reverse sorting order, True or False
proc_reversed = False

#* Show processes as a tree
proc_tree = False

#* Which depth the tree view should auto-collapse packages to
tree_depth = 3

#* Use the cpu graph for the top process line (per-core or total usage)
proc_cpu_graphs = True

#* Show cpu graph for each process
proc_per_core = False

#* Show memory as bytes instead of percent
proc_mem_bytes = True

#* Show cpu info at the top of the "cpu box"
cpu_invert_lower = True

#* Set to True to enable single color gradient in cpu box
cpu_single_graph = False

#* Show cpu box at top-left, top-right, bottom-left or bottom-right
cpu_bottom = False

#* Shows the system uptime in the cpu box
show_uptime = True

#* Show cpu temperature
check_temp = True

#* Which gpu to show stats for in the gpu box
selected_gpu = "Auto"

#* Show memory info as bytes instead of percent
mem_graphs = True

#* Show mem box below net box instead of above
mem_below_net = False

#* Count ZFS ARC in cached and available memory
zfs_arc_cached = True

#* If swap memory should be shown in the mem box
show_swap = True

#* Show swap as a disk, ignores show_swap value above, and forces swap to not be shown in mem box
swap_disk = True

#* If proc box should be shown on left side of screen, default is right
proc_left = False

#* Sets the filtering in to all processes, not just the ones matching the current search
proc_filter_kernel = False

#* Enable vim keys for the cpu box
vim_mode = True
